#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef WATCHFACESDK_SWIFT_H
#define WATCHFACESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import SFDialPlateSDK;
@import SifliOTAManagerSDK;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WatchfaceSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class SFOTAManager;
@class SFOTAError;
SWIFT_CLASS("_TtC12WatchfaceSDK18HwOTAUpdateManager")
@interface HwOTAUpdateManager : NSObject <SFOTAManagerDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)otaManagerWithManager:(SFOTAManager * _Nonnull)manager updateBleState:(enum BleCoreManagerState)state;
- (void)otaManagerWithManager:(SFOTAManager * _Nonnull)manager stage:(enum SFOTAProgressStage)stage totalBytes:(NSInteger)totalBytes completedBytes:(NSInteger)completedBytes;
- (void)otaManagerWithManager:(SFOTAManager * _Nonnull)manager complete:(SFOTAError * _Nullable)error;
@end

@class UIImage;
@class NSString;
SWIFT_CLASS("_TtC12WatchfaceSDK15LsQjsAlbumModel")
@interface LsQjsAlbumModel : NSObject
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS("_TtC12WatchfaceSDK11LsQjsWidget")
@interface LsQjsWidget : NSObject
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger width;
@property (nonatomic) NSInteger height;
@property (nonatomic) NSInteger x;
@property (nonatomic) NSInteger y;
@property (nonatomic, strong) UIColor * _Nullable tintColor;
@property (nonatomic) NSInteger valueType;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, QjsAlignment, open) {
  QjsAlignmentTop = 0,
  QjsAlignmentRight = 1,
  QjsAlignmentBottom = 2,
  QjsAlignmentLeft = 3,
};

SWIFT_CLASS("_TtC12WatchfaceSDK17QjsIconDataWidget")
@interface QjsIconDataWidget : LsQjsWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK16QjsBatteryWidget")
@interface QjsBatteryWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
SWIFT_PROTOCOL("_TtP12WatchfaceSDK11QjsCallback_")
@protocol QjsCallback
/// zip file will be deleted, if return true, if you don’t want it to be deleted, override callback return false, or you can save the file before returning true
/// @param zip
- (void)onZipCompletedWithZip:(NSURL * _Nonnull)zip;
- (void)onErrorWithCode:(NSInteger)code;
- (void)onQjsSaved;
- (void)onProgressWithCurrent:(int64_t)current total:(int64_t)total;
- (void)onSuccess;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK16QjsCalorieWidget")
@interface QjsCalorieWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK13QjsDateWidget")
@interface QjsDateWidget : LsQjsWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK17QjsDistanceWidget")
@interface QjsDistanceWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK12QjsDotWidget")
@interface QjsDotWidget : LsQjsWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK18QjsDurationsWidget")
@interface QjsDurationsWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, QjsError, open) {
  QjsErrorNone = 0,
  QjsErrorUnknownError = 4000,
  QjsErrorCreateDirError = 4100,
  QjsErrorSaveBinFileError = 4102,
  QjsErrorZipError = 4200,
  QjsErrorExportBinError = 4300,
  QjsErrorSaveQjsFileError = 4400,
  QjsErrorQjsFileEmpty = 4440,
  QjsErrorSaveAodQjsFileError = 4401,
  QjsErrorMissingThumbnail = 4501,
  QjsErrorMissingWidgetImages = 4504,
  QjsErrorManualStop = 4766,
};

@class NSData;
SWIFT_CLASS("_TtC12WatchfaceSDK12QjsFileUtils")
@interface QjsFileUtils : NSObject
+ (NSData * _Nullable)exportBinWithSource:(UIImage * _Nonnull)source color:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK18QjsHeartrateWidget")
@interface QjsHeartrateWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK16QjsPointerWidget")
@interface QjsPointerWidget : LsQjsWidget
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12WatchfaceSDK20QjsHourPointerWidget")
@interface QjsHourPointerWidget : QjsPointerWidget
@end

SWIFT_CLASS("_TtC12WatchfaceSDK22QjsMinutePointerWidget")
@interface QjsMinutePointerWidget : QjsPointerWidget
@end

SWIFT_CLASS("_TtC12WatchfaceSDK22QjsSecondPointerWidget")
@interface QjsSecondPointerWidget : QjsPointerWidget
@end

SWIFT_CLASS("_TtC12WatchfaceSDK13QjsStepWidget")
@interface QjsStepWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK15QjsStorageUtils")
@interface QjsStorageUtils : NSObject
+ (void)saveString:(NSString * _Nonnull)str forKey:(NSString * _Nonnull)key;
+ (NSString * _Nullable)getStringForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)getDataForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (void)save:(id _Nonnull)v forKey:(NSString * _Nonnull)key;
+ (id _Nullable)getForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)saveAsFileForString:(NSString * _Nonnull)string fileName:(NSString * _Nonnull)fileName SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)saveAsFileForData:(NSData * _Nonnull)data fileName:(NSString * _Nonnull)fileName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDocPath SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getCahcePath SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getTempPath SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isFileExitsAtPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)createPathWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)moveItemFromPath:(NSString * _Nonnull)fromPath toPath:(NSString * _Nonnull)toPath SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)copyItemFromPath:(NSString * _Nonnull)fromPath toPath:(NSString * _Nonnull)toPath SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)deleteFileAtPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (void)deleteFilesAtPath:(NSString * _Nonnull)path;
+ (NSData * _Nullable)getDataAtPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nullable)getFilesAtDirectory:(NSString * _Nonnull)directory SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK13QjsTimeWidget")
@interface QjsTimeWidget : LsQjsWidget
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, QjsValueType, open) {
  QjsValueTypeNone = -1,
  QjsValueTypeStepsNum = 0,
  QjsValueTypeCalorieNum = 1,
  QjsValueTypeHeartrateNum = 2,
  QjsValueTypeTemperatureNum = 4,
  QjsValueTypeTemperatureTypeNum = 73,
  QjsValueTypeBatteryNum = 9,
  QjsValueTypeHourNum = 12,
  QjsValueTypeMinuteNum = 13,
  QjsValueTypeSecondNum = 14,
  QjsValueTypeHourPointer = 150,
  QjsValueTypeMinutePointer = 153,
  QjsValueTypeSecondPointer = 154,
  QjsValueTypeWeekData = 52,
  QjsValueTypeDateNum = 17,
  QjsValueTypeDistanceNum = 146,
  QjsValueTypeWeatherNum = 21,
  QjsValueTypeActivityTime = 214,
};

SWIFT_CLASS("_TtC12WatchfaceSDK18QjsWeatherTAWidget")
@interface QjsWeatherTAWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK16QjsWeatherWidget")
@interface QjsWeatherWidget : QjsIconDataWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK13QjsWeekWidget")
@interface QjsWeekWidget : LsQjsWidget
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTintColor:(UIColor * _Nonnull)tintColor OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK17SifliQjsWatchface")
@interface SifliQjsWatchface : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
@class SlifiCustomWatchface;
SWIFT_CLASS("_TtC12WatchfaceSDK17SifliWatchfaceSDK")
@interface SifliWatchfaceSDK : NSObject
@property (nonatomic) double width;
@property (nonatomic) double height;
@property (nonatomic, copy) void (^ _Nullable ProgressCallback)(NSInteger);
@property (nonatomic, copy) void (^ _Nullable FinishCallback)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable CompressSuccessCallback)(BOOL);
@property (nonatomic) BOOL isWorking;
+ (SifliWatchfaceSDK * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)initSDK SWIFT_METHOD_FAMILY(none);
/// \param devIdentifier The identifier string of the target device. Through CBPeripheral. Identifier. UuidString acquisition
///
/// \param compressSuccessCallback Compressed file callback
///
/// \param albums QjsAlbumModel array
///
/// \param progressCallback Synchronization progress callback
///
/// \param finishCallback Synchronization completes the callback
///
- (void)setPicturesWithDevIdentifier:(NSString * _Nonnull)devIdentifier compressSuccessCallback:(void (^ _Nonnull)(BOOL))compressSuccessCallback albums:(NSArray<LsQjsAlbumModel *> * _Nonnull)albums progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
/// \param devIdentifier The identifier string of the target device. Through CBPeripheral. Identifier. UuidString acquisition
///
/// \param musicFilePath The music file must be in the: music/mp3 directory
///
/// \param compressSuccessCallback Compressed file callback
///
/// \param progressCallback Synchronization progress callback
///
/// \param finishCallback Synchronization completes the callback
///
- (void)setMusicFilesWithDevIdentifier:(NSString * _Nonnull)devIdentifier musicFilePath:(NSURL * _Nonnull)musicFilePath compressCallback:(void (^ _Nonnull)(BOOL))compressCallback progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
- (void)pushOfflineMapWithDevIdentifier:(NSString * _Nonnull)devIdentifier mapZipFilePath:(NSURL * _Nonnull)mapZipFilePath compressCallback:(void (^ _Nonnull)(BOOL))compressCallback progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
/// \param devIdentifier The identifier string of the target device. Through CBPeripheral. Identifier. UuidString acquisition
///
/// \param watchface set SlifiCustomWatchface argument
///
/// \param compressSuccessCallback Compressed file callback
///
/// \param progressCallback Synchronization progress callback
///
/// \param finishCallback Synchronization completes the callback
///
- (void)setCustomWatchfaceWithDevIdentifier:(NSString * _Nonnull)devIdentifier watchface:(SlifiCustomWatchface * _Nonnull)watchface compressSuccessCallback:(void (^ _Nonnull)(BOOL))compressSuccessCallback progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
/// \param devIdentifier The identifier string of the target device. Through CBPeripheral. Identifier. UuidString acquisition
///
/// \param filePath Online Dial file Path
///
/// \param compressSuccessCallback Compressed file callback
///
/// \param progressCallback Synchronization progress callback
///
/// \param finishCallback Synchronization completes the callback
///
- (void)setOnlineWatchfaceWithDevIdentifier:(NSString * _Nonnull)devIdentifier filePath:(NSURL * _Nonnull)filePath progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
- (void)syncZipFileWithDevIdentifier:(NSString * _Nonnull)devIdentifier filePath:(NSURL * _Nonnull)filePath type:(NSInteger)type progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
- (void)syncZipFileWithDevIdentifier:(NSString * _Nonnull)devIdentifier filePath:(NSURL * _Nonnull)filePath type:(NSInteger)type byteAlign:(BOOL)byteAlign progressCallback:(void (^ _Nonnull)(NSInteger))progressCallback finishCallback:(void (^ _Nonnull)(BOOL, NSString * _Nullable, NSInteger, NSNumber * _Nonnull))finishCallback;
/// Abort task。
- (void)stop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SFDialPlateManager;
@class SFError;
@interface SifliWatchfaceSDK (SWIFT_EXTENSION(WatchfaceSDK)) <SFDialPlateManagerDelegate>
- (void)dialPlateManagerWithManager:(SFDialPlateManager * _Nonnull)manager didUpdateBLEState:(enum DPBleCoreManagerState)bleState;
- (void)dialPlateManagerWithManager:(SFDialPlateManager * _Nonnull)manager progress:(NSInteger)progress;
- (void)dialPlateManagerWithManager:(SFDialPlateManager * _Nonnull)manager complete:(SFError * _Nullable)error;
@end

SWIFT_CLASS("_TtC12WatchfaceSDK20SlifiCustomWatchface")
@interface SlifiCustomWatchface : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger width;
@property (nonatomic) NSInteger height;
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@property (nonatomic, strong) UIImage * _Nullable thumbnailImage;
@property (nonatomic, copy) NSURL * _Nullable backgroundGif;
@property (nonatomic, copy) NSArray<LsQjsWidget *> * _Nonnull widgetList;
- (nonnull instancetype)initWithWidth:(NSInteger)width height:(NSInteger)height OBJC_DESIGNATED_INITIALIZER;
- (void)addWidget:(LsQjsWidget * _Nonnull)widget;
- (void)removeWidget:(LsQjsWidget * _Nonnull)widget;
- (void)removeWidgetById:(NSInteger)id;
- (void)removeAllWidgets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface UIImage (SWIFT_EXTENSION(WatchfaceSDK))
- (UIImage * _Nonnull)imageByTintColorWithColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)resize:(CGSize)size cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)imageWithColorWithColor:(UIColor * _Nonnull)color size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)loadImageWithNamed:(NSString * _Nonnull)imgName SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
