source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/sususu/LYSpecs.git'

use_frameworks!

platform :ios, '10.0'

target 'AiSDK_Example' do
  pod 'SVProgressHUD'
  pod 'ReactiveObjC'
  pod 'AiSDK', :git => 'https://github.com/HWdan/HwAiSDK.git', :branch => 'main'
  pod 'WatchfaceSDK', :git => 'https://github.com/HWdan/WatchfaceSDK.git', :branch => 'main'
  target 'AiSDK_Tests' do
    inherit! :search_paths

    
  end
end
